// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZSY7Ev8Fs3BjGKyVbIzRY4F3pvE_1MHY',
    appId: '1:570859300172:web:f87a346ff9d65ae6a85be9',
    messagingSenderId: '570859300172',
    projectId: 'gymnutricion-d70a8',
    authDomain: 'gymnutricion-d70a8.firebaseapp.com',
    storageBucket: 'gymnutricion-d70a8.appspot.com',
    measurementId: 'G-Y26E97VDKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMYWkFGdHIK9NZMC_Lnsx2iKA_yxrZN0k',
    appId: '1:570859300172:android:8b89e98a08cfe649a85be9',
    messagingSenderId: '570859300172',
    projectId: 'gymnutricion-d70a8',
    storageBucket: 'gymnutricion-d70a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC5vU6o4DuSMPspr3ZsVA1OMFYM_y4Be8',
    appId: '1:570859300172:ios:b0fd73ad93cb66d1a85be9',
    messagingSenderId: '570859300172',
    projectId: 'gymnutricion-d70a8',
    storageBucket: 'gymnutricion-d70a8.appspot.com',
    androidClientId: '570859300172-coj22jf909aq22bk9k26tpnlah7dm9go.apps.googleusercontent.com',
    iosClientId: '570859300172-ld556vnedphpustk7fnk8q89k4om886e.apps.googleusercontent.com',
    iosBundleId: 'com.gym.administrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC5vU6o4DuSMPspr3ZsVA1OMFYM_y4Be8',
    appId: '1:570859300172:ios:b0fd73ad93cb66d1a85be9',
    messagingSenderId: '570859300172',
    projectId: 'gymnutricion-d70a8',
    storageBucket: 'gymnutricion-d70a8.appspot.com',
    androidClientId: '570859300172-coj22jf909aq22bk9k26tpnlah7dm9go.apps.googleusercontent.com',
    iosClientId: '570859300172-ld556vnedphpustk7fnk8q89k4om886e.apps.googleusercontent.com',
    iosBundleId: 'com.gym.administrador',
  );
}
